### PR TITLE
Added new functions for getting the raw transaction data

### PR DESCRIPTION
**Pull request by Gz75y45ms3kc**
I have added two new functions to bitcash.network.NetworkAPI, namely get_raw_transaction and get_raw_transaction_testnet. I needed them to access some of the blockchain data that wasn't available in the other functions.
Also, I tweaked some of the other functions as they did not seem to be calling the (t)rest.bitcoin.com API correctly.

P.S. this is my first pull request on any github project, so apologies in advance for any mistakes/conventions not followed.

### CODE REVIEW

**Comment by teran-mckinney** [comment]
Thanks for the pull request. Do tests pass with this change? Probably worth adding tests as well with a couple transactions to be sure the output stays stable.

I see get_transaction() is altered heavily which is my main concern if anyone else is using it and expecting particular output.

@merc1er, what do you think?

**Comment by merc1er** [comment]
`test_get_transactions_test_equal()` seems to fail.

> I see get_transaction() is altered heavily which is my main concern if anyone else is using it and expecting particular output.

I agree, I'm not sure why it is modified as it doesn't seem to be used by `get_raw_transaction`.

**Comment by Gz75y45ms3kc** [comment]
The two are separate. I wanted to both have the new functions included and provide fixes for what I saw as not working correctly. It would be more appropriate to split them into two separate pull requests? I'm happy to do that.

What motivated the suggested fixes were the following: 

- The url: https://rest.bitcoin.com/v2/tx/ gives a 404 error (same for trest.bitcoin.com). This affects MAIN_TX_API and MAIN_TX_AMOUNT_API
- The line "TEST_TX_API = MAIN_TX_API" does not make sense to me as the TEST and MAIN APIs have different base urls

I wasn't aware of (and am still not completely familiar with) the testing mechanism. My own manual testing amounted to using the hosts file to black hole the bitcore.io domain. Some of the functions stopped working, so I tweaked them until they did. I didn't run the test script before submitting, but have run it since. I am also seeing test_get_transactions_test_equal() failing, but not knowing where to look to see what is actually going on.
Can you help me understand the testing? Does it just run the functions and check to see if an exception is thrown, or is it checking the outputs are as expected? If the latter, where are the inputs and outputs specified?

**Comment by merc1er** [comment]
> It would be more appropriate to split them into two separate pull requests? I'm happy to do that.

Yes please :) or at least two separate commits. But yes PRs would be best I guess.

> The url: https://rest.bitcoin.com/v2/tx/ gives a 404 error (same for trest.bitcoin.com). This affects MAIN_TX_API and MAIN_TX_AMOUNT_API

That's correct, this is some stuff I copied from `InsightAPI` and that I did not change. Thanks for noticing!

Don't worry about testing, I can take care of it. It is done `tests` folder, I'll work on that when you have the PRs ready 😄

**Comment by teran-mckinney** [comment]
Closing in favor of #55

**Pull request closed without merging**
