### PR TITLE
Fixed BCH to Fiat API endpoint

### PR DESCRIPTION
**Pull request by merc1er**
Related to #29 👍

### CODE REVIEW

**Comment by BUYMERCIER** [comment]
@lannocc @AustEcon

**Comment by AustEcon** [comment]
Code looks good to my eyes. 
I've just done similar thing for bitsv (http://bitcoinsv-rates.com/api/rates/ endpoint) and is basically the same api setup. Looks good to me. 👍 
Cheers

**Comment by BUYMERCIER** [comment]
@teran-mckinney

**Comment by teran-mckinney** [comment]
Hey! Sorry for the wait on this.

Do we have any test coverage for this? I might have broken those.

Thanks for making a fix.

**Comment by merc1er** [comment]
Hi!

So I ran tests and mainly one external API is not passing: `TestCashExplorerBitcoinDotComAPI`

This is because Bitcoin.com changed their infrastructure for this service and the endpoint is wrong (no longer cash explorer.bitcoin.com)
I will be working on this later.

The fiat conversion works with BitPay API.

I also worked on fixing the documentation and ported to Python 3.7. I will be submitting some other PRs

**Comment by teran-mckinney** [comment]
Awesome, thank you!

**Pull request merged**
