### PR TITLE
Add raw tx 3

### PR DESCRIPTION
**Pull request by Gz75y45ms3kc**
Replaced the if status code, raise ConnectionError with r.raise_for_status() as per merc1er and  teran-mckinney suggestions.

### CODE REVIEW

**Comment by teran-mckinney** [comment]
This is the successor to #52 which is the successor to #51. By the way, you can use the same PR and push to that branch :).

Thanks for sending this over. Will take a look.

**Comment by teran-mckinney** [comment]
@merc1er what do you think? Whenever you get the chance.

**Comment by merc1er** [comment]
Looks good, but why is it this in a new PR?

**Comment by merc1er** [comment]
I tested #52 it seemed to work fine! You can go ahead and merge this and close #51 and #51 everything is fine with you @teran-mckinney 😄   
I will then implement tests for that.

**Comment by merc1er** [comment]
@teran-mckinney could you release a new version on PyPi? @Gz75y45ms3kc might need to use the new functions in his apps 😄

**Comment by teran-mckinney** [comment]
Done!

**Pull request merged**
