### PR TITLE
Add OP_PUSHDATA1, 2 and 4

### PR DESCRIPTION
**Pull request by cyborg0922**
Adds OP_PUSHDATA1 or OP_PUSHDATA2 op codes for 76-255 and >255 byte OP_RETURN data respectively.

### CODE REVIEW

**Comment by lannocc** [comment]
Small nit: `len(dest)` gets called a minimum of 2 and up to 3 times in your code. Assigning it to a variable instead improves performance (function calls are costly).

**Comment by cyborg0922** [comment]
Cheers!
- I've noticed that there's an issue with fees when setting fee = 1 sat/byte... using this... ended up with only 0.6 sat / byte... The one time I have to do a CPFP we get a goddamned 44 minute long block time (and counting!) - FML... I'm confident it will go through and confirm... just was stupid setting fee to 1 sat / byte. 
- We need to fix how this is calculated but can't tonight.

**Comment by teran-mckinney** [comment]
Can you rebase this?

I have always set fees to 2 at smallest, but I'm sure we can fix the logic there.

**Comment by cyborg0922** [comment]
Yep. I'll rebase when I get home tonight :) might leave fixing the fee for another PR or someone else if that's alright with you?

**Comment by teran-mckinney** [comment]
Thank you!

**Pull request merged**
